# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ce35e0d9e00708cb3560c2494ff404dcae21b0b5f43172b0dd859c6260e82da7daf1b2959f9cc9ec958e6c49a800893a3450e5a99790ef90d93a4f699442671

test:
  secret_key_base: 828da7ce0b7f6e132d1de8ef8b37f15eb69dc200a3c6da92f89fe19ebdb6d8ed9ed0a29fe822ad14f1ed622435e8683faa683df7669eff3baa724f2ef43ef275

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
